config/routes.rb
Rails.application.routes.draw do
  resources :external_services_params
  root 'home#index'
   get "/users" => redirect("/")
    devise_for :users

  get '/users/user_index' => 'users#user_index', :as => 'user_index'
  get '/users/validator_index' => 'users#validator_index', :as => 'validator_index'
  get '/users/index' => 'users#index', :as => 'main_users'
  get '/users/new' => 'users#new', :as => 'user_new'
  get '/users/new_validator' => 'users#new_validator', :as => 'user_new_validator'
  post '/users/create' => 'users#create', :as => 'user_create'
  get '/users/:id/edit' => 'users#edit', :as => 'user_edit'
  get '/users/:id/scanner_edit' => 'users#scanner_edit', :as => 'scanner_edit'
  get '/users/:id' => 'users#show', :as => 'user_show'
  put '/users/:id' => 'user#update', :as => 'user_update'
  patch '/users/:id' => 'users#update'
  delete '/users/:id' => 'users#destroy', :as => 'user_delete'
  post '/unlock_user' => 'users#unlock_user'

  get '/roles/role_index' => 'roles#role_index', :as => 'role_index'

  get '/home/home_index' => 'home#home_index', :as => 'home_index'

  get '/region_masters/region_master_index' => 'region_masters#region_master_index', :as => 'region_master_index'
  get '/city_town_masters/city_town_master_index' => 'city_town_masters#city_town_master_index', :as => 'city_town_master_index'
  get '/suburb_masters/suburb_master_index' => 'suburb_masters#suburb_master_index', :as => 'suburb_master_index'

  get '/activity_types/activity_type_index' => 'activity_types#activity_type_index', :as => 'activity_type_index'

  get '/activity_categories/activity_category_index' => 'activity_categories#activity_category_index', :as => 'activity_category_index'
  get '/activity_groups/activity_group_index' => 'activity_groups#activity_group_index', :as => 'activity_group_index'

  get '/assigned_fees/assigned_fee_index' => 'assigned_fees#assigned_fee_index', :as => 'assigned_fee_index'

  get '/entity_categories/entity_category_index' => 'entity_categories#entity_category_index', :as => 'entity_category_index'
  get '/entity_infos/entity_info_index' => 'entity_infos#entity_info_index', :as => 'entity_info_index'

  get '/entity_divisions/entity_division_index/:entity_code' => 'entity_divisions#entity_division_index', :as => 'entity_division_index'
  get '/entity_divisions/entity_division_index' => 'entity_divisions#entity_division_index', :as => 'entity_div_index'
  get '/entity_divisions/entity_index' => 'entity_divisions#entity_index', :as => 'entity_index'
  get '/entity_infos/sports_index' => 'entity_infos#sports_index', :as => 'sports_index'
  get '/entity_divisions/main_sports_index/:entity_code' => 'entity_divisions#main_sports_index', :as => 'main_sports_index'
  get '/entity_divisions/main_sports_index' => 'entity_divisions#main_sports_index'
  post '/entity_divisions/entity_div_create' => 'entity_divisions#entity_div_create', :as => 'entity_div_create'

  get '/entity_divisions/division_setup/:division_code' => 'entity_divisions#division_setup', :as => 'division_setup'
  post '/division_setup_creation' => 'entity_divisions#create_division_setup', :as => 'create_division_setup'
  get '/entity_divisions/division_edit_setup/:division_code' => 'entity_divisions#division_edit_setup', :as => 'division_edit_setup'
  post '/division_setup_update' => 'entity_divisions#update_division_setup', :as => 'update_division_setup'
  post '/reset_qr_code' => 'entity_divisions#reset_qr_code', :as => 'reset_biz_qr_code'

  get '/entity_divisions/sport_setup/:division_code' => 'entity_divisions#sport_setup', :as => 'sport_setup'
  post '/sport_setup_creation' => 'entity_divisions#create_sport_setup', :as => 'create_sport_setup'
  get '/entity_divisions/sport_edit_setup/:division_code' => 'entity_divisions#sport_edit_setup', :as => 'sport_edit_setup'
  post '/sport_setup_update' => 'entity_divisions#update_sport_setup', :as => 'update_sport_setup'

  get '/entity_div_alert_recipients/entity_div_alert_recipient_index' => 'entity_div_alert_recipients#entity_div_alert_recipient_index', :as => 'entity_div_alert_recipient_index'

  get '/entity_divisions/fixture_new/:division_code' => 'entity_divisions#fixture_new', :as => 'fixture_new'
  post '/fixture_creation' => 'entity_divisions#create_fixture', :as => 'create_fixture'
  get '/entity_divisions/fixture_edit/:act_div_id' => 'entity_divisions#fixture_edit', :as => 'fixture_edit'
  patch '/fixture_update/:act_div_id' => 'entity_divisions#update_fixture', :as => 'update_fixture'

  get '/entity_admin_whitelists/entity_admin_whitelist_index' => 'entity_admin_whitelists#entity_admin_whitelist_index', :as => 'entity_admin_whitelist_index'

  get '/activity_divs/activity_div_index' => 'activity_divs#activity_div_index', :as => 'activity_div_index'

  get '/entity_div_media/entity_div_media_index' => 'entity_div_media#entity_div_media_index', :as => 'entity_div_media_index'
  get '/entity_div_media/image_media' => 'entity_div_media#image_media', :as => 'image_media'
  get '/entity_div_media/video_media' => 'entity_div_media#video_media', :as => 'video_media'
  get '/entity_div_social_handles/entity_div_social_handle_index' => 'entity_div_social_handles#entity_div_social_handle_index', :as => 'entity_div_social_handle_index'
  get 'inner_new' => 'entity_div_media#inner_new', :as => 'inner_new'
  post 'inner_create' => 'entity_div_media#inner_create', :as => 'media_inner_create'
  get '/inner_del/:id' => 'entity_div_media#inner_destroy', :as => 'inner_destroy'

  get '/activity_type_media/activity_type_media_index' => 'activity_type_media#activity_type_media_index', :as => 'activity_type_media_index'
  get '/activity_type_media/image_media' => 'activity_type_media#image_media', :as => 'act_image_media'
  get '/activity_type_media/video_media' => 'activity_type_media#video_media', :as => 'act_video_media'
  get 'inner_new' => 'activity_type_media#inner_new', :as => 'act_inner_new'
  post 'inner_create' => 'activity_type_media#inner_create', :as => 'act_media_inner_create'
  get '/inner_del/:id' => 'activity_type_media#inner_destroy', :as => 'act_inner_destroy'

  get '/fund_movements/settlement_entity_info_index' => 'fund_movements#settlement_entity_info_index', :as => 'settlement_entity_info_index'
  get '/fund_movements/settlement_entity_division_index/:entity_code' => 'fund_movements#settlement_entity_division_index', :as => 'settlement_entity_division_index'
  get '/fund_movements/settlement_entity_division_index' => 'fund_movements#settlement_entity_division_index', :as => 'settlement_entity_div_index'
  get '/fund_movements/fund_movement_index/:division_code' => 'fund_movements#fund_movement_index', :as => 'fund_movement_index'
  get '/fund_movements/fund_movement_index' => 'fund_movements#fund_movement_index', :as => 'fund_move_index'

  get '/payment_infos/payment_info_index' => 'payment_infos#payment_info_index', :as => 'payment_info_index'
  patch '/payment_infos/transaction_resend/:id' => 'payment_infos#transaction_resend', :as => 'transaction_resend'
  post '/payment_infos/transaction_resend/:id' => 'payment_infos#transaction_resend', :as => 'transactions_resend'
  get '/payment_infos/resend_form/:id' => 'payment_infos#resend_form', :as => 'resend_form'
  get '/payment_infos/resend_show/:id' => 'payment_infos#resend_show', :as => 'resend_show'

  get '/payment_infos/financial_index' => 'payment_infos#financial_index', :as => 'financial_index'
  get '/payment_infos/financial_statement_index' => 'payment_infos#financial_statement_index', :as => 'financial_statement_index'
  get '/payment_infos/wallet_statement_index' => 'payment_infos#wallet_statement_index', :as => 'wallet_statement_index'
  get '/payment_infos/financial_form' => 'payment_infos#financial_form', :as => 'financial_form'
  post '/payment_infos/financial_search' => 'payment_infos#financial_search', :as => 'financial_search'
  post '/payment_infos/wallet_search' => 'payment_infos#wallet_search', :as => 'wallet_search'

  get '/activity_participants/activity_participant_index' => 'activity_participants#activity_participant_index', :as => 'activity_participant_index'
  get '/activity_fixtures/activity_fixture_index' => 'activity_fixtures#activity_fixture_index', :as => 'activity_fixture_index'
  get '/activity_div_cats/activity_div_cat_index' => 'activity_div_cats#activity_div_cat_index', :as => 'activity_div_cat_index'
  get '/activity_category_divs/activity_category_div_index/:div_cat_id' => 'activity_category_divs#activity_category_div_index', :as => 'activity_category_div_index'

  get '/sub_activity_masters/sub_activity_master_index' => 'sub_activity_masters#sub_activity_master_index', :as => 'sub_activity_master_index'
  get '/entity_div_sub_activities/entity_div_sub_activity_index' => 'entity_div_sub_activities#entity_div_sub_activity_index', :as => 'entity_div_sub_activity_index'

  get '/loan_requests/loan_request_index' => 'loan_requests#loan_request_index', :as => 'loan_request_index'
  get '/client_webhook_configs/client_webhook_index' => 'client_webhook_configs#client_webhook_index', :as => 'client_webhook_index'
  get '/entity_div_ref_lookups/entity_div_ref_lookup_index' => 'entity_div_ref_lookups#entity_div_ref_lookup_index', :as => 'entity_div_ref_lookup_index'

  get '/reports' => 'dashboard#index', :as => 'reports'
  get '/report_index' => 'dashboard#report_index', :as => 'report_index'

  post '/suburb_masters/city_update', :as => 'suburb_city_ajax_call'
  post '/suburb_masters/suburb_update', :as => 'general_suburb_ajax_call'
  post '/entity_divisions/category_div_update', :as => 'div_cat_to_cat_div_ajax_call'
  post '/entity_divisions/fixture_update', :as => 'cat_div_to_fixture_ajax_call'
  post '/entity_divisions/division_update', :as => 'general_division_ajax_call'
  post '/entity_divisions/lov_update', :as => 'general_lov_ajax_call'
  post '/entity_divisions/ref_update', :as => 'general_ref_ajax_call'

app/models/fund_movement.rb
class FundMovement < ApplicationRecord
  self.table_name="fund_movement"
  self.primary_key = "id"

  belongs_to :entity_division, class_name: "EntityDivision", foreign_key: :entity_div_code


  def self.to_csv(general_report, current_user, options = "")
    CSV.generate(options) do |csv|
      #headers = %w{Merchant Service Reference Selected_Option Activity_Type Mobile_No Name/Reference Network Tranx_ID Gross_Amount Charge Actual_Amount Source Status Date}
      if current_user.super_admin? || current_user.super_user?
        headers = %w{Merchant Service Service_ID Ref_ID Amount Narration Trans_Type Trans_Status Trans_Description Status Date Time}
      else
        headers = %w{Merchant Service Ref_ID Amount Narration Trans_Type Trans_Description Status Date Time}
      end
      csv << headers

      general_report.each do |summary|
        # ------code comes here

        logger.info "General report :: #{summary.inspect}"
        entity_div = EntityDivision.where(active_status: true, assigned_code: summary.entity_div_code).order(created_at: :desc).first
        if entity_div
          ent_info = EntityInfo.where(active_status: true, assigned_code: entity_div.entity_code).order(created_at: :desc).first
          if ent_info
            merchant = ent_info.entity_name
          else
            merchant = ""
          end
          service = entity_div.division_name
        else
          merchant = ""
          service = ""
        end

        #service = summary.entity_division ? summary.entity_division.division_name : ""


        if summary.processed
          status = "Processed"
        elsif summary.processed == false
          status = "Failed"
        else
          status = "Pending"
        end
        date = summary.created_at
        for_date = summary.created_at.strftime('%Y-%m-%d')
        for_time = summary.created_at.strftime('%H:%M:%S')
        if current_user.super_admin? || current_user.super_user?
          csv << [merchant, service, summary.service_id, summary.ref_id, summary.amount, summary.narration, summary.trans_type, summary.trans_status, summary.trans_desc, status, for_date, for_time] #[merchant, rec_name, summary.pc_name, summary.momo_number, summary.product_name, bags, quantity, summary.amount, summary.exttrid, status, summary.date]
        else
          csv << [merchant, service, summary.ref_id, summary.amount, summary.narration, summary.trans_type, summary.trans_desc, status, for_date, for_time] #[merchant, rec_name, summary.pc_name, summary.momo_number, summary.product_name, bags, quantity, summary.amount, summary.exttrid, status, summary.date]
        end
      end

    end
  end


end

app/helpers/fund_movements_helper.rb
module FundMovementsHelper
end

app/views/fund_movements/_form.html.erb
<%= simple_form_for(@fund_movement) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :entity_div_code %>
    <%= f.input :service_id %>
    <%= f.input :ref_id %>
    <%= f.input :amount %>
    <%= f.input :narration %>
    <%= f.input :trans_type %>
    <%= f.input :trans_status %>
    <%= f.input :trans_desc %>
    <%= f.input :processed %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/fund_movements/_settlement_entity_division_index.html.erb

<div>
  <br>
  <p id="notes2"><%#= notice %></p>
  <p id="for_division_setup"><%#= notice %></p>
  <h4><%= @entity_name %></h4>
  <br>
  <div>
    <% if current_user.super_admin? || current_user.super_user? #|| current_user.merchant_admin? %>
      <div class="w3-half">

        <% if current_user.super_admin? || current_user.super_user? #|| current_user.merchant_admin? %>
          <%= link_to 'BACK', settlement_entity_info_index_path(count: params[:count], page: params[:page], entity_name: params[:entity_name],
                                                                assigned_code: params[:assigned_code], entity_cat: params[:entity_cat]), style: "width:120px;",
                      class: 'w3-button w3-white w3-border w3-border-purple w3-small w3-round-large',remote:true %>
        <% end %>
      </div>
      <div class="w3-half">
        <%= select_tag :count1, options_for_select([50, 100, 150, 200, 500], params[:count1].to_i),
                       :data => {  :remote => true, :url => url_for(:controller => "fund_movements", :action => "settlement_entity_division_index",
                                                                    :params => {entity_code: params[:entity_code],entity_name: params[:entity_name],
                                                                                assigned_code: params[:assigned_code], entity_cat: params[:entity_cat],
                                                                                count: params[:count], page: params[:page]})},
                       id:"record", class: "w3-button w3-white w3-border w3-border-purple w3-round-large",
                       style: "width:auto; height:35px; float:right", remote:true %>
      </div>
    <% elsif current_user.merchant_admin? %>
      <div class="">
        <%= select_tag :count1, options_for_select([50, 100, 150, 200, 500], params[:count1].to_i),
                       :data => {  :remote => true, :url => url_for(:controller => "fund_movements", :action => "settlement_entity_division_index",
                                                                    :params => {entity_code: params[:entity_code],
                                                                                count: params[:count], page: params[:page]})},
                       id:"record", class: "w3-button w3-white w3-border w3-border-purple w3-round-large",
                       style: "width:auto; height:35px; float:right", remote:true %>

      </div>
    <% end %>

  </div>
  <br>
  <div class="table-responsive-md">
    <br>
    <table class="table w3-responsive table-striped">
      <thead>
      <tr>
<!--        <th></th>-->
        <th>ID</th>
        <th>Service Name</th>
        <th>Activity Type</th>
        <th>Status</th>
        <th>Date</th>
        <th></th>
      </tr>
      </thead>
      <tbody>
      <% @entity_divisions.each do |entity_division| %>

        <tr>
          <td><strong><%= entity_division.assigned_code %></strong></td>
          <!--            <td><strong><%#= entity_division.division_name %> <%##= entity_division.division_alias %></strong></td>-->
          <td><strong><%= entity_division.division_name.length > 21 ? "#{entity_division.division_name[0..21]}.." : entity_division.division_name %></strong></td>

          <td><strong><%= entity_division.activity_type.activity_type_desc %> <%#= entity_info.entity_category.assigned_code %></strong></td>
          <% if entity_division.active_status %>
            <td><strong>Active</strong></td>
          <% else %>
            <td><strong>Inactive</strong></td>
          <% end %>
          <td><strong><%= entity_division.created_at %></strong></td>

          <td>

            <%= link_to 'SETTLEMENTS', fund_movement_index_path(entity_division, entity_name: params[:entity_name], assigned_code: params[:assigned_code],
                                                                entity_cat: params[:entity_cat], entity_code: params[:entity_code], count1: params[:count1], page1: params[:page1], count: params[:count], page: params[:page]),
                        style: "width:120px; height: 30px;",
                        class: 'w3-button w3-purple-vpos w3-border w3-border-purple w3-tiny w3-round-large', remote:true%>

          </td>

        </tr>

      <% end %>


      </tbody>
    </table>
    <% unless params[:count1] == "All" %>
      <div class="flickr_pagination"  style="float: right">
        <%= will_paginate @entity_divisions, class: "w3-card", renderer: BootstrapPagination::Rails,
                          :params => { :controller => "fund_movements", :action => "settlement_entity_division_index", entity_code: params[:entity_code],entity_name: params[:entity_name], assigned_code: params[:assigned_code],
                                       entity_cat: params[:entity_cat], count1: params[:count1], page1: params[:page1], count: params[:count], page: params[:page] } %>
        <%#= js_will_paginate @payment_infos, :params => { :controller => "payment_infos", :action => "payment_info_index" } %>
      </div>
    <% end %>
  </div>


</div>



<script>
    $(function(){
        $('.pagination a').attr('data-remote', 'true')
    });

</script>

app/views/fund_movements/_settlement_entity_info_index.html.erb

<div>
  <br>
  <p id="notes1"><%#= notice %></p>
  <br>
  <div>
    <!--<div class="w3-half">-->
    <%#= link_to 'NEW', new_entity_info_path(count: params[:count], page: params[:page]), style: "width:120px;",
                  class: 'w3-button w3-purple-vpos w3-border w3-border-purple w3-small w3-round-large',remote:true %>
    <!--</div>-->
    <div class="w3-half">
      <button onclick="document.getElementById('settle').style.display='block'" class="w3-btn btn btn-outline-purple tablink w3-vpos-purple">Filter</button>
      <%#= link_to 'FILTER', onclick: "document.getElementById('settle').style.display='block'", style: "font-size: small; width: 150px;", class: 'btn btn-outline-purple tablink w3-vpos-purple' %>
    </div>

    <%#
      #if params[:filter_main].present?
      #  params[:filter_main] = params[:filter_main].to_unsafe_h
      #else
      #  params[:filter_main] = ""
      #end
    %>



    <div class="w3-half">
      <%= select_tag :count, options_for_select([50, 100, 150, 200, 500], params[:count].to_i),
                     :data => {  :remote => true, :url => url_for(:controller => "fund_movements", :action => "settlement_entity_info_index",
                                                                  :params => {
                                                                      entity_name: params[:entity_name], assigned_code: params[:assigned_code],
                                                                      entity_cat: params[:entity_cat]
                                                                  })},
                     id:"record", class: "w3-button w3-white w3-border w3-border-purple w3-round-large",
                     style: "width:auto; height:35px; float:right", remote:true %>

    </div>
  </div>
  <br>
  <div class="table-responsive-md">
    <br>
    <table class="table w3-responsive table-striped">
      <thead>
      <tr>
        <!--<th></th>-->
        <th>ID</th>
        <th>Merchant Name (Merchant Alias)</th>
        <!--        <th>Activity Code</th>-->
        <th>Category</th>
        <th>Status</th>
        <th>Date</th>
        <th></th>
      </tr>
      </thead>
      <tbody>
      <% @entity_infos.each do |entity_info| %>


        <tr>
          <!--<td><%#= link_to 'VIEW', entity_info_path(entity_info, count: params[:count], page: params[:page]),
                            style: "width:100px; height: 30px;",
                            class: 'w3-button w3-purple-vpos w3-border w3-border-purple w3-tiny w3-round-large', remote:true%></td>-->
          <td><strong><%= entity_info.assigned_code %></strong></td>
          <!--            <td><strong><%#= entity_info.entity_name %> (<%#= entity_info.entity_alias %>)</strong></td>-->
          <td><strong><%= entity_info.entity_name.length > 25 ? "#{entity_info.entity_name[0..25]}.." : entity_info.entity_name %> (<%= entity_info.entity_alias.length > 20 ? "#{entity_info.entity_alias[0..20]}.." : entity_info.entity_alias %>)</strong></td>

          <!--            <td><strong><%#= entity_info.entity_name %></strong></td>-->
          <td><strong><%= entity_info.entity_cat_id if entity_info.entity_cat_id != nil %> <%#= entity_info.entity_category.assigned_code %></strong></td>

          <% if entity_info.active_status %>
            <td><strong>Active</strong></td>
          <% else %>
            <td><strong>Inactive</strong></td>
          <% end %>
          <td><strong><%= entity_info.created_at %></strong></td>
          <td>
            <%= link_to 'SERVICES', settlement_entity_division_index_path(entity_info, entity_name: params[:entity_name], assigned_code: params[:assigned_code],
                                                                          entity_cat: params[:entity_cat], count1: params[:count1], page1: params[:page1], count: params[:count], page: params[:page]),
                        style: "width:120px; height: 30px;",
                        class: 'w3-button w3-purple-vpos w3-border w3-border-purple w3-tiny w3-round-large', remote:true%></td>
        </tr>

      <% end %>

      </tbody>
    </table>
    <% unless params[:count] == "All" %>
      <div class="flickr_pagination"  style="float: right">
        <%= will_paginate @entity_infos, class: "w3-card", renderer: BootstrapPagination::Rails,
                          :params => { :controller => "fund_movements", :action => "settlement_entity_info_index", count: params[:count], page: params[:page] } %>
        <%#= js_will_paginate @payment_infos, :params => { :controller => "payment_infos", :action => "payment_info_index" } %>
      </div>
    <% end %>
  </div>


</div>



<div class="w3-container" >
  <div id="settle" class="w3-modal w3-animate-opacity" style=" display: none">
    <span onclick="document.getElementById('settle').style.display='none'"
          class="w3-button w3-display-topright">&times;</span>
    <!--<div class="w3-modal-content w3-card-4" >-->
    <br/>
    <%#= render 'form' %>

    <div class="">
      <div class="w3-white w3-hover-shadow col-md-4 offset-md-4 w3-card-4 w3-border w3-border-purple rcorners w3-center">
        <h4 class="show w3-center"><strong>Filter Merchants</strong></h4>
        <div id="entity_info_edit"></div>
        <%#= simple_form_for(@entity_info, :data => {  :remote => true, count: params[:count], page: params[:page]}) do |f| %>
        <%= simple_form_for :filter_main, :url => (settlement_entity_info_index_path(count: params[:count], page: params[:page])), :method => 'get', html: {class: 'form-horizontal'}, remote: true do |f| %>
          <div class="w3-container w3-border w3-border-purple">
            <br/>
            <input type="hidden" class="form-control" name="count" value="<%= params[:count] %>"/>
            <input type="hidden" class="form-control" name="page" value="<%= params[:page] %>"/>
            <!--                    <input type="hidden" class="form-control" name="counter" value="<%#= params[:counter] %>"/>-->
            <!--                    <input type="hidden" class="form-control" name="pager" value="<%#= params[:pager] %>"/>-->
            <!--          <input type="hidden" class="form-control" name="entity_code" value="<%#= @entity_code %>"/>-->
            <!--          <input type="hidden" class="form-control" name="code" value="<%#= @code %>"/>-->
            <div class="">

              <%#=
                select_tag "filter_main[entity_name]",
                           options_from_collection_for_select(@merchant_search, entity_name, assigned_code), {:class => 'form-control', :id => 'id_entity_info', :style => "width: 180px"}
              %>



              <%#= f.select(:trial, @merchant_search.collect {|p| [p.entity_name, p.assigned_code]}, {include_blank: "None"}, {id: "id_trial"}) %>
              <%= f.input :entity_name, collection: @merchant_search, label_method: :entity_name, value_method: :assigned_code, input_html: {id: "merchanter", style: "width: 100%;"}, label: "Merchant Name", boolean_style: :inline %>
              <%= f.input :assigned_code, class: "form-control", collection: @merchant_code_search, label_method: :assigned_code, value_method: :assigned_code, input_html: {id: "id_entity_info_ass", style: "width: 100%;", autocomplete: "off"}, label: "Assigned Code", boolean_style: :inline %>
              <%= f.input :entity_cat, class: "form-control", collection: @merchant_cat_search, label_method: :entity_cat_name_join, value_method: :assigned_code, input_html: {id: "id_entity_cat", style: "width: 100%;", autocomplete: "off"}, label: "Entity Category", boolean_style: :inline %>

            </div>


            <br/>
          </div>

          <br>

          <div>
            <br><br>
            <%= f.submit "Filter", class: "w3-button w3-purple-vpos w3-border w3-border-purple w3-small w3-round-large", :data => {:disable_with => 'Searching...'}, style: "width:auto;float:center;",remote:true %>
            <%#= link_to 'Back', entity_info_index_path(page: params[:page], count: params[:count]), class: "w3-button w3-white w3-border w3-border-purple w3-small w3-round-large",remote:true %>
            <button type="button" onclick="document.getElementById('settle').style.display='none'" class="w3-button w3-white w3-border w3-border-purple w3-small w3-round-large">Back</button>


            <br><br>
          </div>
        <% end %>


      </div>

    </div>


    <div class="col-md-7 col-md-offset-5">
    </div>

    <br/>
    <div class="col-md-7 col-md-offset-5">
      <br/>
      <br/>
    </div>
    <!--</div>-->

  </div>
</div>



<script>
    $(function(){
        $('.pagination a').attr('data-remote', 'true');
    });


    (function($){
        "use strict";
        $(document).on('turbolinks:load', function() {
            $("#id_trial").select2({
                allowClear: true,
                theme: "bootstrap"
            });
            $("#id_entity_info").select2({
                allowClear: true,
                theme: "bootstrap"
            });
        });
    }(jQuery));

</script>

app/views/fund_movements/edit.html.erb
<h1>Editing Fund Movement</h1>

<%= render 'form', fund_movement: @fund_movement %>

<%= link_to 'Show', @fund_movement %> |
<%= link_to 'Back', fund_movements_path %>

app/views/fund_movements/fund_movement_index.js.erb
$("#fund_movement").html("<%= escape_javascript(render(:partial =>"fund_movement_index")) %>");
$('#notes3').html("<%= escape_javascript(render 'layouts/messages') %>");

app/views/fund_movements/new.html.erb
<h1>New Fund Movement</h1>

<%= render 'form', fund_movement: @fund_movement %>

<%= link_to 'Back', fund_movements_path %>

app/views/fund_movements/settlement_entity_division_index.js.erb
$("#fund_movement").html("<%= escape_javascript(render(:partial =>"settlement_entity_division_index")) %>");
$('#notes2').html("<%= escape_javascript(render 'layouts/messages') %>");

app/views/fund_movements/settlement_entity_info_index.js.erb
$("#fund_movement").html("<%= escape_javascript(render(:partial =>"settlement_entity_info_index")) %>");
$('#notes1').html("<%= escape_javascript(render 'layouts/messages') %>");

app/views/fund_movements/show.js.erb
$("#notes3").html("<%= escape_javascript(render(:partial =>"show")) %>");
$('#notice3').html("<%= escape_javascript(render 'layouts/messages') %>");