config/routes.rb
Rails.application.routes.draw do
  resources :external_services_params
  root 'home#index'
   get "/users" => redirect("/")
    devise_for :users

  get '/users/user_index' => 'users#user_index', :as => 'user_index'
  get '/users/validator_index' => 'users#validator_index', :as => 'validator_index'
  get '/users/index' => 'users#index', :as => 'main_users'
  get '/users/new' => 'users#new', :as => 'user_new'
  get '/users/new_validator' => 'users#new_validator', :as => 'user_new_validator'
  post '/users/create' => 'users#create', :as => 'user_create'
  get '/users/:id/edit' => 'users#edit', :as => 'user_edit'
  get '/users/:id/scanner_edit' => 'users#scanner_edit', :as => 'scanner_edit'
  get '/users/:id' => 'users#show', :as => 'user_show'
  put '/users/:id' => 'user#update', :as => 'user_update'
  patch '/users/:id' => 'users#update'
  delete '/users/:id' => 'users#destroy', :as => 'user_delete'
  post '/unlock_user' => 'users#unlock_user'

  get '/roles/role_index' => 'roles#role_index', :as => 'role_index'

  get '/home/home_index' => 'home#home_index', :as => 'home_index'

  get '/region_masters/region_master_index' => 'region_masters#region_master_index', :as => 'region_master_index'
  get '/city_town_masters/city_town_master_index' => 'city_town_masters#city_town_master_index', :as => 'city_town_master_index'
  get '/suburb_masters/suburb_master_index' => 'suburb_masters#suburb_master_index', :as => 'suburb_master_index'

  get '/activity_types/activity_type_index' => 'activity_types#activity_type_index', :as => 'activity_type_index'

  get '/activity_categories/activity_category_index' => 'activity_categories#activity_category_index', :as => 'activity_category_index'
  get '/activity_groups/activity_group_index' => 'activity_groups#activity_group_index', :as => 'activity_group_index'

  get '/assigned_fees/assigned_fee_index' => 'assigned_fees#assigned_fee_index', :as => 'assigned_fee_index'

  get '/entity_categories/entity_category_index' => 'entity_categories#entity_category_index', :as => 'entity_category_index'
  get '/entity_infos/entity_info_index' => 'entity_infos#entity_info_index', :as => 'entity_info_index'

  get '/entity_divisions/entity_division_index/:entity_code' => 'entity_divisions#entity_division_index', :as => 'entity_division_index'
  get '/entity_divisions/entity_division_index' => 'entity_divisions#entity_division_index', :as => 'entity_div_index'
  get '/entity_divisions/entity_index' => 'entity_divisions#entity_index', :as => 'entity_index'
  get '/entity_infos/sports_index' => 'entity_infos#sports_index', :as => 'sports_index'
  get '/entity_divisions/main_sports_index/:entity_code' => 'entity_divisions#main_sports_index', :as => 'main_sports_index'
  get '/entity_divisions/main_sports_index' => 'entity_divisions#main_sports_index'
  post '/entity_divisions/entity_div_create' => 'entity_divisions#entity_div_create', :as => 'entity_div_create'

  get '/entity_divisions/division_setup/:division_code' => 'entity_divisions#division_setup', :as => 'division_setup'
  post '/division_setup_creation' => 'entity_divisions#create_division_setup', :as => 'create_division_setup'
  get '/entity_divisions/division_edit_setup/:division_code' => 'entity_divisions#division_edit_setup', :as => 'division_edit_setup'
  post '/division_setup_update' => 'entity_divisions#update_division_setup', :as => 'update_division_setup'
  post '/reset_qr_code' => 'entity_divisions#reset_qr_code', :as => 'reset_biz_qr_code'

  get '/entity_divisions/sport_setup/:division_code' => 'entity_divisions#sport_setup', :as => 'sport_setup'
  post '/sport_setup_creation' => 'entity_divisions#create_sport_setup', :as => 'create_sport_setup'
  get '/entity_divisions/sport_edit_setup/:division_code' => 'entity_divisions#sport_edit_setup', :as => 'sport_edit_setup'
  post '/sport_setup_update' => 'entity_divisions#update_sport_setup', :as => 'update_sport_setup'

  get '/entity_div_alert_recipients/entity_div_alert_recipient_index' => 'entity_div_alert_recipients#entity_div_alert_recipient_index', :as => 'entity_div_alert_recipient_index'

  get '/entity_divisions/fixture_new/:division_code' => 'entity_divisions#fixture_new', :as => 'fixture_new'
  post '/fixture_creation' => 'entity_divisions#create_fixture', :as => 'create_fixture'
  get '/entity_divisions/fixture_edit/:act_div_id' => 'entity_divisions#fixture_edit', :as => 'fixture_edit'
  patch '/fixture_update/:act_div_id' => 'entity_divisions#update_fixture', :as => 'update_fixture'

  get '/entity_admin_whitelists/entity_admin_whitelist_index' => 'entity_admin_whitelists#entity_admin_whitelist_index', :as => 'entity_admin_whitelist_index'

  get '/activity_divs/activity_div_index' => 'activity_divs#activity_div_index', :as => 'activity_div_index'

  get '/entity_div_media/entity_div_media_index' => 'entity_div_media#entity_div_media_index', :as => 'entity_div_media_index'
  get '/entity_div_media/image_media' => 'entity_div_media#image_media', :as => 'image_media'
  get '/entity_div_media/video_media' => 'entity_div_media#video_media', :as => 'video_media'
  get '/entity_div_social_handles/entity_div_social_handle_index' => 'entity_div_social_handles#entity_div_social_handle_index', :as => 'entity_div_social_handle_index'
  get 'inner_new' => 'entity_div_media#inner_new', :as => 'inner_new'
  post 'inner_create' => 'entity_div_media#inner_create', :as => 'media_inner_create'
  get '/inner_del/:id' => 'entity_div_media#inner_destroy', :as => 'inner_destroy'

  get '/activity_type_media/activity_type_media_index' => 'activity_type_media#activity_type_media_index', :as => 'activity_type_media_index'
  get '/activity_type_media/image_media' => 'activity_type_media#image_media', :as => 'act_image_media'
  get '/activity_type_media/video_media' => 'activity_type_media#video_media', :as => 'act_video_media'
  get 'inner_new' => 'activity_type_media#inner_new', :as => 'act_inner_new'
  post 'inner_create' => 'activity_type_media#inner_create', :as => 'act_media_inner_create'
  get '/inner_del/:id' => 'activity_type_media#inner_destroy', :as => 'act_inner_destroy'

  get '/fund_movements/settlement_entity_info_index' => 'fund_movements#settlement_entity_info_index', :as => 'settlement_entity_info_index'
  get '/fund_movements/settlement_entity_division_index/:entity_code' => 'fund_movements#settlement_entity_division_index', :as => 'settlement_entity_division_index'
  get '/fund_movements/settlement_entity_division_index' => 'fund_movements#settlement_entity_division_index', :as => 'settlement_entity_div_index'
  get '/fund_movements/fund_movement_index/:division_code' => 'fund_movements#fund_movement_index', :as => 'fund_movement_index'
  get '/fund_movements/fund_movement_index' => 'fund_movements#fund_movement_index', :as => 'fund_move_index'

  get '/payment_infos/payment_info_index' => 'payment_infos#payment_info_index', :as => 'payment_info_index'
  patch '/payment_infos/transaction_resend/:id' => 'payment_infos#transaction_resend', :as => 'transaction_resend'
  post '/payment_infos/transaction_resend/:id' => 'payment_infos#transaction_resend', :as => 'transactions_resend'
  get '/payment_infos/resend_form/:id' => 'payment_infos#resend_form', :as => 'resend_form'
  get '/payment_infos/resend_show/:id' => 'payment_infos#resend_show', :as => 'resend_show'

  get '/payment_infos/financial_index' => 'payment_infos#financial_index', :as => 'financial_index'
  get '/payment_infos/financial_statement_index' => 'payment_infos#financial_statement_index', :as => 'financial_statement_index'
  get '/payment_infos/wallet_statement_index' => 'payment_infos#wallet_statement_index', :as => 'wallet_statement_index'
  get '/payment_infos/financial_form' => 'payment_infos#financial_form', :as => 'financial_form'
  post '/payment_infos/financial_search' => 'payment_infos#financial_search', :as => 'financial_search'
  post '/payment_infos/wallet_search' => 'payment_infos#wallet_search', :as => 'wallet_search'

  get '/activity_participants/activity_participant_index' => 'activity_participants#activity_participant_index', :as => 'activity_participant_index'
  get '/activity_fixtures/activity_fixture_index' => 'activity_fixtures#activity_fixture_index', :as => 'activity_fixture_index'
  get '/activity_div_cats/activity_div_cat_index' => 'activity_div_cats#activity_div_cat_index', :as => 'activity_div_cat_index'
  get '/activity_category_divs/activity_category_div_index/:div_cat_id' => 'activity_category_divs#activity_category_div_index', :as => 'activity_category_div_index'

  get '/sub_activity_masters/sub_activity_master_index' => 'sub_activity_masters#sub_activity_master_index', :as => 'sub_activity_master_index'
  get '/entity_div_sub_activities/entity_div_sub_activity_index' => 'entity_div_sub_activities#entity_div_sub_activity_index', :as => 'entity_div_sub_activity_index'

  get '/loan_requests/loan_request_index' => 'loan_requests#loan_request_index', :as => 'loan_request_index'
  get '/client_webhook_configs/client_webhook_index' => 'client_webhook_configs#client_webhook_index', :as => 'client_webhook_index'
  get '/entity_div_ref_lookups/entity_div_ref_lookup_index' => 'entity_div_ref_lookups#entity_div_ref_lookup_index', :as => 'entity_div_ref_lookup_index'

  get '/reports' => 'dashboard#index', :as => 'reports'
  get '/report_index' => 'dashboard#report_index', :as => 'report_index'

  post '/suburb_masters/city_update', :as => 'suburb_city_ajax_call'
  post '/suburb_masters/suburb_update', :as => 'general_suburb_ajax_call'
  post '/entity_divisions/category_div_update', :as => 'div_cat_to_cat_div_ajax_call'
  post '/entity_divisions/fixture_update', :as => 'cat_div_to_fixture_ajax_call'
  post '/entity_divisions/division_update', :as => 'general_division_ajax_call'
  post '/entity_divisions/lov_update', :as => 'general_lov_ajax_call'
  post '/entity_divisions/ref_update', :as => 'general_ref_ajax_call'

app/models/entity_div_sub_activity.rb
class EntityDivSubActivity < ApplicationRecord
  self.table_name="entity_div_sub_activity"
  self.primary_key = :id

  belongs_to :sub_activity_master, class_name: "SubActivityMaster", foreign_key: :sub_activity_code
  belongs_to :entity_division, class_name: "EntityDivision", foreign_key: :entity_div_code

  validates :sub_activity_code, presence: {message: " cannot be empty."}
  validates :entity_div_code, presence: {message: " cannot be empty."}
  validates :div_sub_activity_desc, presence: {message: " cannot be empty."}

end

app/helpers/entity_div_sub_activities_helper.rb
module EntityDivSubActivitiesHelper
end

app/views/entity_div_sub_activities/_edit.html.erb
<div class="w3-container" >
  <div id="id01" class="w3-modal w3-animate-opacity" style=" display: block">
    <!--<div class="w3-modal-content w3-card-4" >-->
    <br/>

    <div class="">

      <div class="w3-white w3-hover-shadow col-md-4 offset-md-4 w3-card-4 w3-border w3-border-purple rcorners w3-center">
        <h4 class="show w3-center"><strong>Edit Activity Code</strong></h4>

        <div class="w3-container">
          <br/>
          <%= simple_form_for(@entity_div_sub_activity, url: entity_div_sub_activity_path(@entity_div_sub_activity, code: params[:code], entity_code: params[:entity_code], count1: params[:count1], page1: params[:page1], count3: params[:count3], page3: params[:page3], count: params[:count], page: params[:page] ),:remote => true) do |f| %>

        <%#= simple_form_for(@entity_div_sub_activity, :data => {  :remote => true, count: params[:count], page: params[:page]}) do |f| %>
            <%= f.error_notification %>
            <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
            <%= f.input :sub_activity_code, collection: @sub_activity_masters,  label: "Activity Code", label_method: :sub_activity_name, value_method: :assigned_code, required: true, input_html:{id: "sub_activity_code", autocomplete: "off",class:"form-control w3-input w3-border w3-white input-group input-append",style:""}  %>

            <%= f.input :div_sub_activity_desc,  label: "Code Description", value_method: :id, required: true, input_html:{id: "for_code_desc", autocomplete: "off",class:"form-control w3-input w3-border w3-white input-group input-append",style:""}  %>

            <%= f.input :active_status, :as => :hidden, input_html:{value: true} %>
            <%= f.input :del_status, :as => :hidden, input_html:{value: false} %>
            <%= f.input :user_id, :as => :hidden, input_html:{value: current_user.id} %>
            <div>
              <%= f.submit "Submit", class: "w3-button w3-purple-vpos w3-border w3-border-purple w3-small w3-round-large", :data => {:disable_with => 'Please Wait...'}, style: "width:auto;float:center;",remote:true %>
              <%= link_to 'Back', entity_div_sub_activity_index_path(code: params[:code], entity_code: params[:entity_code], count1: params[:count1], page1: params[:page1], count3: params[:count3], page3: params[:page3], page: params[:page], count: params[:count]), class: "w3-button w3-white w3-border w3-border-purple w3-small w3-round-large",remote:true %>
            </div>
          <% end %>
          <br/>
        </div>


      </div>

    </div>


    <div class="col-md-7 col-md-offset-5">
    </div>




    <br/>
    <div class="col-md-7 col-md-offset-5">
      <br/>
      <br/>
    </div>
    <!--</div>-->

  </div>
</div>

app/views/entity_div_sub_activities/_entity_div_sub_activity_index.html.erb

<div>
  <br>
  <p id="notes14"><%#= notice %></p>
  <% entity_div = EntityDivision.where(assigned_code: params[:code], active_status: true).order(created_at: :desc).first %>
  <h4>Merchant Activity Code(s) for <%= entity_div.division_name if entity_div %></h4>
  <br>
  <div>
    <div class="w3-half">
      <%= link_to 'NEW', new_entity_div_sub_activity_path(entity_code: params[:entity_code], code: params[:code], count1: params[:count1], count3: params[:count3], count: params[:count], page: params[:page]), style: "width:120px;",
                  class: 'w3-button w3-purple-vpos w3-border w3-border-purple w3-small w3-round-large',remote:true %>
      <%= link_to 'BACK', entity_division_index_path(entity_code: params[:entity_code], code: params[:code], service_filter: session[:service_filter].present? ? session[:service_filter].to_enum.to_h : "", count1: params[:count1], count: params[:count], page: $entity_division_page), style: "width:120px;",
                  class: 'w3-button w3-white w3-border w3-border-purple w3-small w3-round-large',remote:true %>
    </div>
    <div class="w3-half">
      <%= select_tag :count3, options_for_select([50, 100, 150, 200, 500], params[:count3].to_i),
                     :data => {  :remote => true, :url => url_for(:controller => "entity_div_sub_activities", :action => "entity_div_sub_activity_index",
                                                                  :params => {entity_code: params[:entity_code], code: params[:code], count1: params[:count1], count: params[:count], page: params[:page]})},
                     id:"record", class: "w3-button w3-white w3-border w3-border-purple w3-round-large",
                     style: "width:auto; height:35px; float:right", remote:true %>
    </div>
  </div>
  <br>
  <div class="table-responsive-md">
    <br>
    <table class="table w3-responsive table-striped">
      <thead>
      <tr>
        <th></th>
        <th>Activity Code</th>
        <th>Code desc</th>
        <th>Status</th>
        <th>Date</th>
        <th>Actions</th>
      </tr>
      </thead>
      <tbody>
      <% @entity_div_sub_activities.each do |entity_div_sub_activity| %>

        <tr>
          <td><%= link_to 'VIEW', entity_div_sub_activity_path(entity_div_sub_activity, entity_code: params[:entity_code], code: params[:code], count1: params[:count1], count3: params[:count3], count: params[:count], page: params[:page]),
                          style: "width:100px; height: 30px;",
                          class: 'w3-button w3-purple-vpos w3-border w3-border-purple w3-tiny w3-round-large', remote:true%></td>
          <td><strong><%= entity_div_sub_activity.sub_activity_master.activity_desc %> (<%= entity_div_sub_activity.sub_activity_master.assigned_code %>)</strong></td>
          <td><strong><%= entity_div_sub_activity.div_sub_activity_desc %></strong></td>
          <% if entity_div_sub_activity.active_status %>
            <td><strong>Active</strong></td>
          <% else %>
            <td><strong>Inactive</strong></td>
          <% end %>
          <td><strong><%= entity_div_sub_activity.created_at %></strong></td>
          <td>
            <%= link_to 'EDIT', edit_entity_div_sub_activity_path(entity_div_sub_activity, entity_code: params[:entity_code], code: params[:code], count1: params[:count1], count3: params[:count3], count: params[:count], page: params[:page]),
                        style: "width:100px; height: 30px; color: #800754 !important",
                        class: 'w3-button w3-white w3-border w3-border-purple w3-tiny w3-round-large', remote:true%>
            <% if entity_div_sub_activity.active_status %>
              <%= link_to 'DISABLE', entity_div_sub_activity_path(entity_div_sub_activity, entity_code: params[:entity_code], code: params[:code], count1: params[:count1], count3: params[:count3], count: params[:count], page: params[:page]),
                          style: "width:100px; height: 30px; color: #800754 !important",
                          method: :delete, data: { confirm: "Do you wish to disable: #{entity_div_sub_activity.div_sub_activity_desc}?" },
                          class: 'w3-button w3-white w3-border w3-border-purple w3-tiny w3-round-large', remote:true%>
            <% else %>
              <%= link_to 'ENABLE', entity_div_sub_activity_path(entity_div_sub_activity, entity_code: params[:entity_code], code: params[:code], count1: params[:count1], count3: params[:count3], count: params[:count], page: params[:page]),
                          style: "width:100px; height: 30px;",
                          method: :delete, data: { confirm: "Do you wish to enable: #{entity_div_sub_activity.div_sub_activity_desc}?" },
                          class: 'w3-button w3-purple-vpos w3-border w3-border-purple w3-tiny w3-round-large', remote:true%>
            <% end %>

          </td>
        </tr>

      <% end %>
      </tbody>
    </table>
    <% unless params[:count3] == "All" %>
      <div class="flickr_pagination"  style="float: right">
        <%= will_paginate @entity_div_sub_activities, class: "w3-card", renderer: BootstrapPagination::Rails,
                          :params => { :controller => "entity_div_sub_activities", :action => "entity_div_sub_activity_index", entity_code: params[:entity_code], code: params[:code], count1: params[:count1], count3: params[:count3], count: params[:count], page: params[:page] } %>
        <%#= js_will_paginate @payment_infos, :params => { :controller => "payment_infos", :action => "payment_info_index" } %>
      </div>
    <% end %>
  </div>


</div>


<script>
    $(function(){
        $('.pagination a').attr('data-remote', 'true')
    });

</script>

app/views/entity_div_sub_activities/_form.html.erb
<div class="">

  <div class="w3-white w3-hover-shadow col-md-4 offset-md-4 w3-card-4 w3-border w3-border-purple rcorners w3-center">
    <h4 class="show w3-center"><strong>New Activity Code</strong></h4>

    <div class="w3-container">
      <br/>
      <%= simple_form_for(@entity_div_sub_activity, url: entity_div_sub_activities_path(@entity_div_sub_activity, code: params[:code], entity_code: params[:entity_code], count1: params[:count1], page1: params[:page1], count3: params[:count3], page3: params[:page3], count: params[:count], page: params[:page] ),:remote => true) do |f| %>
        <%#= simple_form_for(@entity_div_sub_activity, :data => {  :remote => true, count: params[:count], page: params[:page]}) do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
        <%= f.input :sub_activity_code, collection: @sub_activity_masters,  label: "Activity Code", label_method: :sub_activity_name, value_method: :assigned_code, required: true, input_html:{id: "sub_activity_code", autocomplete: "off",class:"form-control w3-input w3-border w3-white input-group input-append",style:""}  %>

        <%= f.input :div_sub_activity_desc,  label: "Type Description", value_method: :id, required: true, input_html:{id: "for_code_desc", autocomplete: "off",class:"form-control w3-input w3-border w3-white input-group input-append",style:""}  %>

        <%= f.input :entity_div_code, :as => :hidden, input_html:{value: params[:code]} %>
        <%= f.input :active_status, :as => :hidden, input_html:{value: true} %>
        <%= f.input :del_status, :as => :hidden, input_html:{value: false} %>
        <%= f.input :user_id, :as => :hidden, input_html:{value: current_user.id} %>
        <div>
          <%= f.submit "Submit", class: "w3-button w3-purple-vpos w3-border w3-border-purple w3-small w3-round-large", :data => {:disable_with => 'Please Wait...'}, style: "width:auto;float:center;",remote:true %>
          <%= link_to 'Back', entity_div_sub_activity_index_path(entity_code: params[:entity_code], code: params[:code], count1: params[:count1], page1: params[:page1], count3: params[:count3], page3: params[:page3], page: params[:page], count: params[:count]), class: "w3-button w3-white w3-border w3-border-purple w3-small w3-round-large",remote:true %>
        </div>
      <% end %>
      <br/>
    </div>

  </div>

</div>


<div class="col-md-7 col-md-offset-5">
</div>

app/views/entity_div_sub_activities/_show.html.erb
<div class="w3-container" >
  <div id="id01" class="w3-modal w3-animate-opacity" style=" display: block">
    <!--<div class="w3-modal-content w3-card-4" >-->
    <br/>

    <div class="">

      <div class="w3-white w3-hover-shadow col-md-6 offset-md-3 w3-card-4 w3-border w3-border-purple rcorners w3-center">
        <h4 class="show w3-center"><strong>Activity Code Details</strong></h4>
        <p id="notice14"><strong></strong></p>
        <div class="w3-container">
          <br/>

          <table class="w3-table-all table table-bordered w3-hoverable w3-card-4">

            <tr>
              <td class="raw_theme w3-border cell-cust-grad w3-leftbar"><strong>Activity Code:</strong></td>
              <td><strong><%= @entity_div_sub_activity.sub_activity_master.assigned_code %> (<%= @entity_div_sub_activity.sub_activity_master.activity_desc %>)</strong></td>
            </tr>

            <tr>
              <td class="raw_theme w3-border cell-cust-grad w3-leftbar"><strong>Code Description:</strong></td>
              <td><strong><%= @entity_div_sub_activity.div_sub_activity_desc %></strong></td>
            </tr>


            <tr>
              <td class="raw_theme w3-border cell-cust-grad w3-leftbar"><strong>Status:</strong></td>

              <% if @entity_div_sub_activity.active_status %>
                <td><strong>Active</strong></td>
              <% else %>
                <td><strong>Inactive</strong></td>
              <% end %>
            </tr>

            <tr>
              <td class="raw_theme w3-border cell-cust-grad w3-leftbar"><strong>Date:</strong></td>
              <td>
                <strong><%= @entity_div_sub_activity.created_at %></strong>
              </td>
            </tr>

          </table>

          <br/>
          <div class="w3-center">
            <%= link_to 'Back', entity_div_sub_activity_index_path(entity_code: params[:entity_code], code: params[:code], count1: params[:count1], page1: params[:page1], count3: params[:count3], page3: params[:page3], page: params[:page], count: params[:count]), class: 'w3-bar-item w3-btn w3-ripple w3-round-large w3-dark-gray', remote: true %>
          </div>
          <br/>
        </div>

      </div>

    </div>

    <!--</div>-->

  </div>
</div>

app/views/entity_div_sub_activities/destroy.js.erb
$("#entity_division").html("<%= escape_javascript(render(:partial =>"entity_div_sub_activity_index")) %>");
$('#notes14').html("<%= escape_javascript(render 'layouts/messages') %>");
$('.pagination a').attr('data-remote', 'true');

app/views/entity_div_sub_activities/entity_div_sub_activity_index.js.erb
$("#entity_division").html("<%= escape_javascript(render(:partial =>"entity_div_sub_activity_index")) %>");
$('#notes14').html("<%= escape_javascript(render 'layouts/messages') %>");

app/views/entity_div_sub_activities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Entity Div Sub Activities</h1>

<table>
  <thead>
    <tr>
      <th>Sub activity code</th>
      <th>Div sub activity desc</th>
      <th>Entity div code</th>
      <th>User</th>
      <th>Active status</th>
      <th>Del status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entity_div_sub_activities.each do |entity_div_sub_activity| %>
      <tr>
        <td><%= entity_div_sub_activity.sub_activity_code %></td>
        <td><%= entity_div_sub_activity.div_sub_activity_desc %></td>
        <td><%= entity_div_sub_activity.entity_div_code %></td>
        <td><%= entity_div_sub_activity.user_id %></td>
        <td><%= entity_div_sub_activity.active_status %></td>
        <td><%= entity_div_sub_activity.del_status %></td>
        <td><%= link_to 'Show', entity_div_sub_activity %></td>
        <td><%= link_to 'Edit', edit_entity_div_sub_activity_path(entity_div_sub_activity) %></td>
        <td><%= link_to 'Destroy', entity_div_sub_activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Entity Div Sub Activity', new_entity_div_sub_activity_path %>

app/views/entity_div_sub_activities/new.js.erb
$("#notes14").html("<%= escape_javascript(render(:partial =>"new")) %>");
$('#entity_div_sub_activity_new').html("<%= escape_javascript(render 'layouts/messages') %>");