config/routes.rb
Rails.application.routes.draw do
  resources :external_services_params
  root 'home#index'
   get "/users" => redirect("/")
    devise_for :users

  get '/users/user_index' => 'users#user_index', :as => 'user_index'
  get '/users/validator_index' => 'users#validator_index', :as => 'validator_index'
  get '/users/index' => 'users#index', :as => 'main_users'
  get '/users/new' => 'users#new', :as => 'user_new'
  get '/users/new_validator' => 'users#new_validator', :as => 'user_new_validator'
  post '/users/create' => 'users#create', :as => 'user_create'
  get '/users/:id/edit' => 'users#edit', :as => 'user_edit'
  get '/users/:id/scanner_edit' => 'users#scanner_edit', :as => 'scanner_edit'
  get '/users/:id' => 'users#show', :as => 'user_show'
  put '/users/:id' => 'user#update', :as => 'user_update'
  patch '/users/:id' => 'users#update'
  delete '/users/:id' => 'users#destroy', :as => 'user_delete'
  post '/unlock_user' => 'users#unlock_user'

  get '/roles/role_index' => 'roles#role_index', :as => 'role_index'

  get '/home/home_index' => 'home#home_index', :as => 'home_index'

  get '/region_masters/region_master_index' => 'region_masters#region_master_index', :as => 'region_master_index'
  get '/city_town_masters/city_town_master_index' => 'city_town_masters#city_town_master_index', :as => 'city_town_master_index'
  get '/suburb_masters/suburb_master_index' => 'suburb_masters#suburb_master_index', :as => 'suburb_master_index'

  get '/activity_types/activity_type_index' => 'activity_types#activity_type_index', :as => 'activity_type_index'

  get '/activity_categories/activity_category_index' => 'activity_categories#activity_category_index', :as => 'activity_category_index'
  get '/activity_groups/activity_group_index' => 'activity_groups#activity_group_index', :as => 'activity_group_index'

  get '/assigned_fees/assigned_fee_index' => 'assigned_fees#assigned_fee_index', :as => 'assigned_fee_index'

  get '/entity_categories/entity_category_index' => 'entity_categories#entity_category_index', :as => 'entity_category_index'
  get '/entity_infos/entity_info_index' => 'entity_infos#entity_info_index', :as => 'entity_info_index'

  get '/entity_divisions/entity_division_index/:entity_code' => 'entity_divisions#entity_division_index', :as => 'entity_division_index'
  get '/entity_divisions/entity_division_index' => 'entity_divisions#entity_division_index', :as => 'entity_div_index'
  get '/entity_divisions/entity_index' => 'entity_divisions#entity_index', :as => 'entity_index'
  get '/entity_infos/sports_index' => 'entity_infos#sports_index', :as => 'sports_index'
  get '/entity_divisions/main_sports_index/:entity_code' => 'entity_divisions#main_sports_index', :as => 'main_sports_index'
  get '/entity_divisions/main_sports_index' => 'entity_divisions#main_sports_index'
  post '/entity_divisions/entity_div_create' => 'entity_divisions#entity_div_create', :as => 'entity_div_create'

  get '/entity_divisions/division_setup/:division_code' => 'entity_divisions#division_setup', :as => 'division_setup'
  post '/division_setup_creation' => 'entity_divisions#create_division_setup', :as => 'create_division_setup'
  get '/entity_divisions/division_edit_setup/:division_code' => 'entity_divisions#division_edit_setup', :as => 'division_edit_setup'
  post '/division_setup_update' => 'entity_divisions#update_division_setup', :as => 'update_division_setup'
  post '/reset_qr_code' => 'entity_divisions#reset_qr_code', :as => 'reset_biz_qr_code'

  get '/entity_divisions/sport_setup/:division_code' => 'entity_divisions#sport_setup', :as => 'sport_setup'
  post '/sport_setup_creation' => 'entity_divisions#create_sport_setup', :as => 'create_sport_setup'
  get '/entity_divisions/sport_edit_setup/:division_code' => 'entity_divisions#sport_edit_setup', :as => 'sport_edit_setup'
  post '/sport_setup_update' => 'entity_divisions#update_sport_setup', :as => 'update_sport_setup'

  get '/entity_div_alert_recipients/entity_div_alert_recipient_index' => 'entity_div_alert_recipients#entity_div_alert_recipient_index', :as => 'entity_div_alert_recipient_index'

  get '/entity_divisions/fixture_new/:division_code' => 'entity_divisions#fixture_new', :as => 'fixture_new'
  post '/fixture_creation' => 'entity_divisions#create_fixture', :as => 'create_fixture'
  get '/entity_divisions/fixture_edit/:act_div_id' => 'entity_divisions#fixture_edit', :as => 'fixture_edit'
  patch '/fixture_update/:act_div_id' => 'entity_divisions#update_fixture', :as => 'update_fixture'

  get '/entity_admin_whitelists/entity_admin_whitelist_index' => 'entity_admin_whitelists#entity_admin_whitelist_index', :as => 'entity_admin_whitelist_index'

  get '/activity_divs/activity_div_index' => 'activity_divs#activity_div_index', :as => 'activity_div_index'

  get '/entity_div_media/entity_div_media_index' => 'entity_div_media#entity_div_media_index', :as => 'entity_div_media_index'
  get '/entity_div_media/image_media' => 'entity_div_media#image_media', :as => 'image_media'
  get '/entity_div_media/video_media' => 'entity_div_media#video_media', :as => 'video_media'
  get '/entity_div_social_handles/entity_div_social_handle_index' => 'entity_div_social_handles#entity_div_social_handle_index', :as => 'entity_div_social_handle_index'
  get 'inner_new' => 'entity_div_media#inner_new', :as => 'inner_new'
  post 'inner_create' => 'entity_div_media#inner_create', :as => 'media_inner_create'
  get '/inner_del/:id' => 'entity_div_media#inner_destroy', :as => 'inner_destroy'

  get '/activity_type_media/activity_type_media_index' => 'activity_type_media#activity_type_media_index', :as => 'activity_type_media_index'
  get '/activity_type_media/image_media' => 'activity_type_media#image_media', :as => 'act_image_media'
  get '/activity_type_media/video_media' => 'activity_type_media#video_media', :as => 'act_video_media'
  get 'inner_new' => 'activity_type_media#inner_new', :as => 'act_inner_new'
  post 'inner_create' => 'activity_type_media#inner_create', :as => 'act_media_inner_create'
  get '/inner_del/:id' => 'activity_type_media#inner_destroy', :as => 'act_inner_destroy'

  get '/fund_movements/settlement_entity_info_index' => 'fund_movements#settlement_entity_info_index', :as => 'settlement_entity_info_index'
  get '/fund_movements/settlement_entity_division_index/:entity_code' => 'fund_movements#settlement_entity_division_index', :as => 'settlement_entity_division_index'
  get '/fund_movements/settlement_entity_division_index' => 'fund_movements#settlement_entity_division_index', :as => 'settlement_entity_div_index'
  get '/fund_movements/fund_movement_index/:division_code' => 'fund_movements#fund_movement_index', :as => 'fund_movement_index'
  get '/fund_movements/fund_movement_index' => 'fund_movements#fund_movement_index', :as => 'fund_move_index'

  get '/payment_infos/payment_info_index' => 'payment_infos#payment_info_index', :as => 'payment_info_index'
  patch '/payment_infos/transaction_resend/:id' => 'payment_infos#transaction_resend', :as => 'transaction_resend'
  post '/payment_infos/transaction_resend/:id' => 'payment_infos#transaction_resend', :as => 'transactions_resend'
  get '/payment_infos/resend_form/:id' => 'payment_infos#resend_form', :as => 'resend_form'
  get '/payment_infos/resend_show/:id' => 'payment_infos#resend_show', :as => 'resend_show'

  get '/payment_infos/financial_index' => 'payment_infos#financial_index', :as => 'financial_index'
  get '/payment_infos/financial_statement_index' => 'payment_infos#financial_statement_index', :as => 'financial_statement_index'
  get '/payment_infos/wallet_statement_index' => 'payment_infos#wallet_statement_index', :as => 'wallet_statement_index'
  get '/payment_infos/financial_form' => 'payment_infos#financial_form', :as => 'financial_form'
  post '/payment_infos/financial_search' => 'payment_infos#financial_search', :as => 'financial_search'
  post '/payment_infos/wallet_search' => 'payment_infos#wallet_search', :as => 'wallet_search'

  get '/activity_participants/activity_participant_index' => 'activity_participants#activity_participant_index', :as => 'activity_participant_index'
  get '/activity_fixtures/activity_fixture_index' => 'activity_fixtures#activity_fixture_index', :as => 'activity_fixture_index'
  get '/activity_div_cats/activity_div_cat_index' => 'activity_div_cats#activity_div_cat_index', :as => 'activity_div_cat_index'
  get '/activity_category_divs/activity_category_div_index/:div_cat_id' => 'activity_category_divs#activity_category_div_index', :as => 'activity_category_div_index'

  get '/sub_activity_masters/sub_activity_master_index' => 'sub_activity_masters#sub_activity_master_index', :as => 'sub_activity_master_index'
  get '/entity_div_sub_activities/entity_div_sub_activity_index' => 'entity_div_sub_activities#entity_div_sub_activity_index', :as => 'entity_div_sub_activity_index'

  get '/loan_requests/loan_request_index' => 'loan_requests#loan_request_index', :as => 'loan_request_index'
  get '/client_webhook_configs/client_webhook_index' => 'client_webhook_configs#client_webhook_index', :as => 'client_webhook_index'
  get '/entity_div_ref_lookups/entity_div_ref_lookup_index' => 'entity_div_ref_lookups#entity_div_ref_lookup_index', :as => 'entity_div_ref_lookup_index'

  get '/reports' => 'dashboard#index', :as => 'reports'
  get '/report_index' => 'dashboard#report_index', :as => 'report_index'

  post '/suburb_masters/city_update', :as => 'suburb_city_ajax_call'
  post '/suburb_masters/suburb_update', :as => 'general_suburb_ajax_call'
  post '/entity_divisions/category_div_update', :as => 'div_cat_to_cat_div_ajax_call'
  post '/entity_divisions/fixture_update', :as => 'cat_div_to_fixture_ajax_call'
  post '/entity_divisions/division_update', :as => 'general_division_ajax_call'
  post '/entity_divisions/lov_update', :as => 'general_lov_ajax_call'
  post '/entity_divisions/ref_update', :as => 'general_ref_ajax_call'

app/models/sub_activity_master.rb
class SubActivityMaster < ApplicationRecord
  self.table_name="sub_activity_master"
  self.primary_key = :assigned_code
  validates_uniqueness_of :assigned_code

  has_many :entity_div_sub_activities, class_name: "EntityDivSubActivity", foreign_key: :sub_activity_code

  validates :activity_desc, presence: {message: " cannot be empty."}
  validates :assigned_code, presence: {message: " cannot be empty."}

  def sub_activity_name
    "#{activity_desc} (#{assigned_code})"
  end

end

app/controllers/sub_activity_masters_controller.rb
class SubActivityMastersController < ApplicationController
  before_action :set_sub_activity_master, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  before_action :load_permissions
  # GET /sub_activity_masters
  # GET /sub_activity_masters.json

  def index
    params[:count] ? params[:count] : params[:count] = 50
    params[:page] ? params[:page] : params[:page] = 1

    @sub_activity_masters = SubActivityMaster.paginate(:page => params[:page], :per_page => params[:count]).order('created_at desc')
  end


  def sub_activity_master_index
    params[:count] ? params[:count] : params[:count] = 50
    params[:page] ? params[:page] : params[:page] = 1

    @sub_activity_masters = SubActivityMaster.paginate(:page => params[:page], :per_page => params[:count]).order('created_at desc')
  end

  # GET /sub_activity_masters/1
  # GET /sub_activity_masters/1.json
  def show
  end

  # GET /sub_activity_masters/new
  def new
    @sub_activity_master = SubActivityMaster.new
  end

  # GET /sub_activity_masters/1/edit
  def edit
  end

  # POST /sub_activity_masters
  # POST /sub_activity_masters.json
  def create
    @sub_activity_master = SubActivityMaster.new(sub_activity_master_params)

    respond_to do |format|
      if @sub_activity_master.save
        format.html { redirect_to @sub_activity_master, notice: 'Sub activity master was successfully created.' }
        flash.now[:notice] = "Activity Code was successfully created."
        format.js { render :show }
        format.json { render :show, status: :created, location: @sub_activity_master }
      else
        format.html { render :new }
        format.js { render :new }
        format.json { render json: @sub_activity_master.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sub_activity_masters/1
  # PATCH/PUT /sub_activity_masters/1.json
  def update
    respond_to do |format|
      if @sub_activity_master.update(sub_activity_master_params)
        format.html { redirect_to @sub_activity_master, notice: 'Sub activity master was successfully updated.' }
        flash.now[:notice] = "Activity Code was successfully updated."
        format.js { render :show }
        format.json { render :show, status: :ok, location: @sub_activity_master }
      else
        format.html { render :edit }
        format.js { render :edit }
        format.json { render json: @sub_activity_master.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_activity_masters/1
  # DELETE /sub_activity_masters/1.json

  def destroy
    params[:count] ? params[:count] : params[:count] = 50
    params[:page] ? params[:page] : params[:page] = 1

    if @sub_activity_master.active_status
      @sub_activity_master.active_status = false
      @sub_activity_master.save(validate: false)
      @sub_activity_masters = SubActivityMaster.paginate(:page => params[:page], :per_page => params[:count]).order('created_at desc')
      respond_to do |format|
        format.html { redirect_to activity_types_url, notice: 'Occupation master was successfully disabled.' }
        flash.now[:note] = 'Activity Code was successfully disabled.'
        format.js { render :layout => false}
        format.json { head :no_content }
        # window.location.href = "<%= recipe_path(@recipe) %>"
      end

    else
      @sub_activity_master.active_status = true
      @sub_activity_master.save(validate: false)
      @sub_activity_masters = SubActivityMaster.paginate(:page => params[:page], :per_page => params[:count]).order('created_at desc')
      respond_to do |format|
        format.html { redirect_to activity_types_url, notice: 'Allergy master was successfully enabled.' }
        flash.now[:notice] = 'Activity Code was successfully enabled.'
        format.js { render :layout => false }
        format.json { head :no_content }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sub_activity_master
      #@sub_activity_master = SubActivityMaster.find(params[:id])
      @sub_activity_master = SubActivityMaster.where(assigned_code: params[:id]).order('id desc').first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sub_activity_master_params
      params.require(:sub_activity_master).permit(:assigned_code, :activity_desc, :user_id, :active_status, :del_status)
    end
end

app/helpers/sub_activity_masters_helper.rb
module SubActivityMastersHelper
end

app/views/sub_activity_masters/_edit.html.erb
<div class="w3-container" >
  <div id="id01" class="w3-modal w3-animate-opacity" style=" display: block">
    <!--<div class="w3-modal-content w3-card-4" >-->
    <br/>

    <div class="">

      <div class="w3-white w3-hover-shadow col-md-4 offset-md-4 w3-card-4 w3-border w3-border-purple rcorners w3-center">
        <h4 class="show w3-center"><strong>Edit Activity Code</strong></h4>

        <div class="w3-container">
          <br/>
          <%= simple_form_for(@sub_activity_master, :data => {  :remote => true, count: params[:count], page: params[:page]}) do |f| %>
            <%= f.error_notification %>
            <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
            <%= f.input :assigned_code,  label: "Assigned Code",  value_method: :id, required: true, readonly: true, input_html:{id: "for_assigned_code", readonly: true, autocomplete: "off",class:"form-control w3-input w3-border w3-white input-group input-append",style:""}  %>

            <%= f.input :activity_desc,  label: "Code Description", value_method: :id, required: true, input_html:{id: "for_type_desc", autocomplete: "off",class:"form-control w3-input w3-border w3-white input-group input-append",style:""}  %>

            <%#= f.input :comment,  label: "Comment", :as => :text, value_method: :id, required: false, input_html:{rows: 5, cols: 3, autocomplete: "off",class:"form-control w3-border ",style:""}  %>
            <%= f.input :active_status, :as => :hidden, input_html:{value: true} %>
            <%= f.input :del_status, :as => :hidden, input_html:{value: false} %>
            <%= f.input :user_id, :as => :hidden, input_html:{value: current_user.id} %>
            <div>
              <%= f.submit "Submit", class: "w3-button w3-purple-vpos w3-border w3-border-purple w3-small w3-round-large", :data => {:disable_with => 'Please Wait...'}, style: "width:auto;float:center;",remote:true %>
              <%= link_to 'Back', sub_activity_master_index_path(page: params[:page], count: params[:count]), class: "w3-button w3-white w3-border w3-border-purple w3-small w3-round-large",remote:true %>
            </div>
          <% end %>
          <br/>
        </div>


      </div>

    </div>


    <div class="col-md-7 col-md-offset-5">
    </div>




    <br/>
    <div class="col-md-7 col-md-offset-5">
      <br/>
      <br/>
    </div>
    <!--</div>-->

  </div>
</div>

app/views/sub_activity_masters/_form.html.erb
<div class="">

  <div class="w3-white w3-hover-shadow col-md-4 offset-md-4 w3-card-4 w3-border w3-border-purple rcorners w3-center">
    <h4 class="show w3-center"><strong>New Activity Code</strong></h4>

    <div class="w3-container">
      <br/>
      <%= simple_form_for(@sub_activity_master, :data => {  :remote => true, count: params[:count], page: params[:page]}) do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
        <%= f.input :assigned_code,  label: "Assigned Code", value_method: :id, required: true, input_html:{id: "for_assigned_code", autocomplete: "off",class:"form-control w3-input w3-border w3-white input-group input-append",style:""}  %>

        <%= f.input :activity_desc,  label: "Code Description", value_method: :id, required: true, input_html:{id: "for_type_desc", autocomplete: "off",class:"form-control w3-input w3-border w3-white input-group input-append",style:""}  %>

        <%#= f.input :comment,  label: "Comment", :as => :text, value_method: :id, required: false, input_html:{rows: 5, cols: 3, autocomplete: "off",class:"form-control w3-border ",style:""}  %>

        <%= f.input :active_status, :as => :hidden, input_html:{value: true} %>
        <%= f.input :del_status, :as => :hidden, input_html:{value: false} %>
        <%= f.input :user_id, :as => :hidden, input_html:{value: current_user.id} %>
        <div>
          <%= f.submit "Submit", class: "w3-button w3-purple-vpos w3-border w3-border-purple w3-small w3-round-large", :data => {:disable_with => 'Please Wait...'}, style: "width:auto;float:center;",remote:true %>
          <%= link_to 'Back', sub_activity_master_index_path(page: params[:page], count: params[:count]), class: "w3-button w3-white w3-border w3-border-purple w3-small w3-round-large",remote:true %>
        </div>
      <% end %>
      <br/>
    </div>

  </div>

</div>


<div class="col-md-7 col-md-offset-5">
</div>

app/views/sub_activity_masters/_show.html.erb
<div class="w3-container" >
  <div id="id01" class="w3-modal w3-animate-opacity" style=" display: block">
    <!--<div class="w3-modal-content w3-card-4" >-->
    <br/>

    <div class="">

      <div class="w3-white w3-hover-shadow col-md-6 offset-md-3 w3-card-4 w3-border w3-border-purple rcorners w3-center">
        <h4 class="show w3-center"><strong>Activity Code Details</strong></h4>
        <p id="notice1"><strong></strong></p>
        <div class="w3-container">
          <br/>

          <table class="w3-table-all table table-bordered w3-hoverable w3-card-4">

            <tr>
              <td class="raw_theme w3-border cell-cust-grad w3-leftbar"><strong>Assigned Code:</strong></td>
              <td><strong><%= @sub_activity_master.assigned_code %></strong></td>
            </tr>

            <tr>
              <td class="raw_theme w3-border cell-cust-grad w3-leftbar"><strong>Type Description:</strong></td>
              <td><strong><%= @sub_activity_master.activity_desc %></strong></td>
            </tr>

            <tr>
              <td class="raw_theme w3-border cell-cust-grad w3-leftbar"><strong>Status:</strong></td>

              <% if @sub_activity_master.active_status %>
                <td><strong>Active</strong></td>
              <% else %>
                <td><strong>Inactive</strong></td>
              <% end %>
            </tr>



            <tr>
              <td class="raw_theme w3-border cell-cust-grad w3-leftbar"><strong>Date:</strong></td>
              <td>
                <strong><%= @sub_activity_master.created_at %></strong>
              </td>
            </tr>

          </table>

          <br/>
          <div class="w3-center">
            <%= link_to 'Back', sub_activity_master_index_path(page: params[:page], count: params[:count]), class: 'w3-bar-item w3-btn w3-ripple w3-round-large w3-dark-gray', remote: true %>
          </div>
          <br/>
        </div>

      </div>

    </div>

    <!--</div>-->

  </div>
</div>

app/views/sub_activity_masters/_sub_activity_master_index.html.erb

<div>
  <br>
  <p id="notes1"><%#= notice %></p>
  <br>
  <div>
    <div class="w3-half">
      <%= link_to 'NEW', new_sub_activity_master_path(count: params[:count], page: params[:page]), style: "width:120px;",
                  class: 'w3-button w3-purple-vpos w3-border w3-border-purple w3-small w3-round-large',remote:true %>
    </div>
    <div class="w3-half">
      <%= select_tag :count, options_for_select([50, 100, 150, 200, 500], params[:count].to_i),
                     :data => {  :remote => true, :url => url_for(:controller => "sub_activity_masters", :action => "sub_activity_master_index")},
                     id:"record", class: "w3-button w3-white w3-border w3-border-purple w3-round-large",
                     style: "width:auto; height:35px; float:right", remote:true %>

    </div>
  </div>
  <br>
  <div class="table-responsive-md">
    <br>
    <table class="table w3-responsive table-striped">
      <thead>
      <tr>
        <th></th>
        <th>Assigned Code</th>
        <th>Code desc</th>
        <th>Status</th>
        <th>Date</th>
        <th>Actions</th>
      </tr>
      </thead>
      <tbody>
      <% @sub_activity_masters.each do |sub_activity_master| %>
        <tr>
          <td><%= link_to 'VIEW', sub_activity_master_path(sub_activity_master, count: params[:count], page: params[:page]),
                          style: "width:100px; height: 30px;",
                          class: 'w3-button w3-purple-vpos w3-border w3-border-purple w3-tiny w3-round-large', remote:true%></td>
          <td><strong><%= sub_activity_master.assigned_code %></td>
          <td><strong><%= sub_activity_master.activity_desc %></td>
          <% if sub_activity_master.active_status %>
            <td><strong>Active</strong></td>
          <% else %>
            <td><strong>Inactive</strong></td>
          <% end %>
          <td><strong><%= sub_activity_master.created_at %></strong></td>
          <td>
            <%= link_to 'EDIT', edit_sub_activity_master_path(sub_activity_master, count: params[:count], page: params[:page]),
                        style: "width:100px; height: 30px; color: #800754 !important",
                        class: 'w3-button w3-white w3-border w3-border-purple w3-tiny w3-round-large', remote:true%>
            <% if sub_activity_master.active_status %>
              <%= link_to 'DISABLE', sub_activity_master_path(sub_activity_master, count: params[:count], page: params[:page]),
                          style: "width:100px; height: 30px; color: #800754 !important",
                          method: :delete, data: { confirm: "Do you wish to disable: #{sub_activity_master.activity_desc}?" },
                          class: 'w3-button w3-white w3-border w3-border-purple w3-tiny w3-round-large', remote:true%>
            <% else %>
              <%= link_to 'ENABLE', sub_activity_master_path(sub_activity_master, count: params[:count], page: params[:page]),
                          style: "width:100px; height: 30px;",
                          method: :delete, data: { confirm: "Do you wish to enable: #{sub_activity_master.activity_desc}?" },
                          class: 'w3-button w3-purple-vpos w3-border w3-border-purple w3-tiny w3-round-large', remote:true%>
            <% end %>
            <% logger.info "Trial" %>
          </td>
        </tr>

      <% end %>

      </tbody>
    </table>
    <% unless params[:count] == "All" %>
      <div class="flickr_pagination"  style="float: right">
        <%= will_paginate @sub_activity_masters, class: "w3-card", renderer: BootstrapPagination::Rails,
                          :params => { :controller => "sub_activity_masters", :action => "sub_activity_master_index", count: params[:count], page: params[:page] } %>
        <%#= js_will_paginate @payment_infos, :params => { :controller => "payment_infos", :action => "payment_info_index" } %>
      </div>
    <% end %>
  </div>

</div>


<script>
    $(function(){
        $('.pagination a').attr('data-remote', 'true')
    });

</script>

app/views/sub_activity_masters/destroy.js.erb
$("#sub_activity_master").html("<%= escape_javascript(render(:partial =>"sub_activity_master_index")) %>");
$('#notes1').html("<%= escape_javascript(render 'layouts/messages') %>");
$('.pagination a').attr('data-remote', 'true');

app/views/sub_activity_masters/index.html.erb
<div class="container">
  <!--<div class="row">-->
  <h4 style="text-decoration: underline;"><strong>ACTIVITY CODES</strong></h4>

  <div class="w3-responsive">

    <div id="sub_activity_master" class="city active">
      <%= render :partial=> "sub_activity_master_index" %>
    </div>

    <!--</div>-->
  </div>
</div>

app/views/sub_activity_masters/new.html.erb
<h1>New Sub Activity Master</h1>

<%= render 'form', sub_activity_master: @sub_activity_master %>

<%= link_to 'Back', sub_activity_masters_path %>

app/views/sub_activity_masters/new.js.erb
$("#notes1").html("<%= escape_javascript(render(:partial =>"new")) %>");
$('#sub_activity_master_new').html("<%= escape_javascript(render 'layouts/messages') %>");

app/views/sub_activity_masters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Assigned code:</strong>
  <%= @sub_activity_master.assigned_code %>
</p>

<p>
  <strong>Activity desc:</strong>
  <%= @sub_activity_master.activity_desc %>
</p>

<p>
  <strong>User:</strong>
  <%= @sub_activity_master.user_id %>
</p>

<p>
  <strong>Active status:</strong>
  <%= @sub_activity_master.active_status %>
</p>

<p>
  <strong>Del status:</strong>
  <%= @sub_activity_master.del_status %>
</p>

<%= link_to 'Edit', edit_sub_activity_master_path(@sub_activity_master) %> |
<%= link_to 'Back', sub_activity_masters_path %>

app/views/sub_activity_masters/sub_activity_master_index.js.erb
$("#sub_activity_master").html("<%= escape_javascript(render(:partial =>"sub_activity_master_index")) %>");
$('#notes1').html("<%= escape_javascript(render 'layouts/messages') %>");